### Import libraries you'll need

In [1]:
from urbansim_templates import modelmanager as mm
from urbansim_templates.models import LargeMultinomialLogitStep
import orca
import os; os.chdir('../')
import warnings; warnings.simplefilter('ignore')

ModuleNotFoundError: No module named 'urbansim_templates'

### Load data and pre-defined model steps

In [2]:
from scripts import datasources
from scripts import models
from scripts import variables

### Generate accessibility variables

In [3]:
orca.run(['initialize_network_small', 'network_aggregations_small'])

Running step 'initialize_network_small'
Time to execute step 'initialize_network_small': 0.00 s
Running step 'network_aggregations_small'
Computing accessibility variables
Computing units_10000
Computing units_sf_10000
Computing units_mf_10000
Computing pop_10000
Removed 189769 rows because they contain missing values
Computing hh_10000
Removed 189769 rows because they contain missing values
Computing poor_10000
Removed 53114 rows because they contain missing values
Computing renters_10000
Removed 102597 rows because they contain missing values
Computing avg_income_10000
Removed 189769 rows because they contain missing values
Computing jobs_10000
Computing avg_rent_10000
Computing pop_white_10000
Removed 107372 rows because they contain missing values
Computing pop_black_10000
Removed 10541 rows because they contain missing values
Computing pop_asian_10000
Removed 51048 rows because they contain missing values
Computing pop_hisp_10000
Removed 31685 rows because they contain missing values
Computing units_25000
Computing units_sf_25000
Computing units_mf_25000
Computing pop_25000
Removed 189769 rows because they contain missing values
Computing hh_25000
Removed 189769 rows because they contain missing values
Computing poor_25000
Removed 53114 rows because they contain missing values
Computing renters_25000
Removed 102597 rows because they contain missing values
Computing avg_income_25000
Removed 189769 rows because they contain missing values
Computing jobs_25000
Computing avg_rent_25000
Computing pop_white_25000
Removed 107372 rows because they contain missing values
Computing pop_black_25000
Removed 10541 rows because they contain missing values
Computing pop_asian_25000
Removed 51048 rows because they contain missing values
Computing pop_hisp_25000
Removed 31685 rows because they contain missing values
Computing jobs_10000_retail
Computing jobs_25000_retail
Computing jobs_10000_fire
Computing jobs_25000_fire
Computing jobs_10000_tech
Computing jobs_25000_tech
Computing jobs_10000_serv
Computing jobs_25000_serv
         units_10000  units_sf_10000  units_mf_10000      pop_10000  \
count   30826.000000    30826.000000    30826.000000   30826.000000
mean   111656.078125    60759.140625    45984.058594  260260.421875
std     87205.929688    37438.925781    46023.648438  188418.093750
min         0.000000        0.000000        0.000000       0.000000
25%     43964.500000    31221.500000    10558.000000  106498.750000
50%     96821.500000    59398.000000    32530.500000  231983.000000
75%    163121.750000    90068.500000    69672.000000  392361.000000
max    406854.000000   147995.000000   205873.000000  838934.000000

            hh_10000     poor_10000  renters_10000  avg_income_10000  \
count   30826.000000   30826.000000   30826.000000      30826.000000
mean    99092.796875   24263.931641   47250.296875     111233.140625
std     78053.578125   22118.812500   47935.484375      30336.044922
min         0.000000       0.000000       0.000000          0.000000
25%     39192.000000    7992.250000   13226.750000      93095.601562
50%     85626.000000   17596.500000   33240.500000     111716.902344
75%    143069.500000   34093.750000   65630.000000     129615.742188
max    370549.000000  100943.000000  225495.000000     265525.000000

         jobs_10000  avg_rent_10000       ...         pop_asian_25000  \
count   30826.00000    30826.000000       ...             30826.00000
mean   118229.84375     2631.133057       ...            294670.71875
std    107967.21875      755.853394       ...            217588.75000
min         0.00000        0.000000       ...                 0.00000
25%     28940.25000     2328.386353       ...             73012.25000
50%     92305.00000     2704.731201       ...            312618.50000
75%    176939.00000     2981.966370       ...            477998.25000
max    428602.00000     5900.000000       ...            693127.00000

       pop_hisp_25000  jobs_10000_retail  jobs_25000_retail  jobs_10000_fire  \
count    30826.000000       30826.000000       30826.000000     30826.000000
mean    183838.812500       15896.663086       55484.597656      8651.133789
std     110234.398438       14089.761719       33833.371094     10032.525391
min          0.000000           0.000000           0.000000         0.000000
25%      88483.750000        4315.250000       21935.500000      2093.000000
50%     181110.000000       13276.000000       61066.000000      5932.500000
75%     298581.500000       21232.750000       87063.000000     10849.000000
max     351718.000000       61048.000000      103905.000000     48870.000000

       jobs_25000_fire  jobs_10000_tech  jobs_25000_tech  jobs_10000_serv  \
count     30826.000000     30826.000000     30826.000000     30826.000000
mean      30371.357422     18315.990234     63948.664062     10135.660156
std       20591.972656     21676.605469     46754.714844     11016.259766
min           0.000000         0.000000         0.000000         0.000000
25%       10932.000000      2208.000000     16480.250000      2744.000000
50%       31111.500000      9142.500000     64656.000000      6776.000000
75%       42118.000000     28645.000000     98837.000000     13249.750000
max       73607.000000    103005.000000    149697.000000     51636.000000

       jobs_25000_serv
count     30826.000000
mean      34162.972656
std       23409.492188
min           0.000000
25%       11541.000000
50%       32524.000000
75%       50603.750000
max       82062.000000

[8 rows x 36 columns]
Time to execute step 'network_aggregations_small': 159.19 s
Total time to execute iteration 1 with iteration value None: 159.19 s

In [4]:
orca.run(['initialize_network_walk', 'network_aggregations_walk'])

Running step 'initialize_network_walk'
Time to execute step 'initialize_network_walk': 0.00 s
Running step 'network_aggregations_walk'
Computing accessibility variables
Computing units_500_walk
Computing sqft_unit_500_walk
Computing singles_500_walk
Removed 52084 rows because they contain missing values
Computing elderly_hh_500_walk
Removed 34553 rows because they contain missing values
Computing children_500_walk
Removed 189769 rows because they contain missing values
Computing units_sf_500_walk
Computing units_mf_500_walk
Computing pop_500_walk
Removed 189769 rows because they contain missing values
Computing hh_500_walk
Removed 189769 rows because they contain missing values
Computing poor_500_walk
Removed 53114 rows because they contain missing values
Computing rich_500_walk
Removed 38964 rows because they contain missing values
Computing renters_500_walk
Removed 102597 rows because they contain missing values
Computing avg_income_500_walk
Removed 189769 rows because they contain missing values
Computing jobs_500_walk
Computing avg_rent_500_walk
Computing pop_white_500_walk
Removed 107372 rows because they contain missing values
Computing pop_black_500_walk
Removed 10541 rows because they contain missing values
Computing pop_asian_500_walk
Removed 51048 rows because they contain missing values
Computing pop_hisp_500_walk
Removed 31685 rows because they contain missing values
Computing units_1500_walk
Computing sqft_unit_1500_walk
Computing singles_1500_walk
Removed 52084 rows because they contain missing values
Computing elderly_hh_1500_walk
Removed 34553 rows because they contain missing values
Computing children_1500_walk
Removed 189769 rows because they contain missing values
Computing units_sf_1500_walk
Computing units_mf_1500_walk
Computing pop_1500_walk
Removed 189769 rows because they contain missing values
Computing hh_1500_walk
Removed 189769 rows because they contain missing values
Computing poor_1500_walk
Removed 53114 rows because they contain missing values
Computing rich_1500_walk
Removed 38964 rows because they contain missing values
Computing renters_1500_walk
Removed 102597 rows because they contain missing values
Computing avg_income_1500_walk
Removed 189769 rows because they contain missing values
Computing jobs_1500_walk
Computing avg_rent_1500_walk
Computing pop_white_1500_walk
Removed 107372 rows because they contain missing values
Computing pop_black_1500_walk
Removed 10541 rows because they contain missing values
Computing pop_asian_1500_walk
Removed 51048 rows because they contain missing values
Computing pop_hisp_1500_walk
Removed 31685 rows because they contain missing values
Computing pop_2500_walk
Removed 189769 rows because they contain missing values
Computing pop_white_2500_walk
Removed 107372 rows because they contain missing values
Computing pop_black_2500_walk
Removed 10541 rows because they contain missing values
Computing pop_asian_2500_walk
Removed 51048 rows because they contain missing values
Computing pop_hisp_2500_walk
Removed 31685 rows because they contain missing values
Computing jobs_500_walk_retail
Computing jobs_1500_walk_retail
Computing jobs_2500_walk_retail
Computing jobs_500_walk_fire
Computing jobs_1500_walk_fire
Computing jobs_2500_walk_fire
Computing jobs_500_walk_tech
Computing jobs_1500_walk_tech
Computing jobs_2500_walk_tech
Computing jobs_500_walk_serv
Computing jobs_1500_walk_serv
Computing jobs_2500_walk_serv
       units_500_walk  sqft_unit_500_walk  singles_500_walk  \
count   415716.000000       415716.000000     415716.000000
mean       356.008972         1245.544556         94.347931
std       1097.037720          979.879944        344.431244
min          0.000000            0.000000          0.000000
25%          9.000000          458.249519          1.000000
50%        188.000000         1315.694275         27.000000
75%        440.000000         1761.837921         87.000000
max     184995.000000        30000.000000      45809.000000

       elderly_hh_500_walk  children_500_walk  units_sf_500_walk  \
count        415716.000000      415716.000000      415716.000000
mean             58.482273         158.034760         163.916275
std             241.357803         443.152496         704.597778
min               0.000000           0.000000           0.000000
25%               1.000000           3.000000           2.000000
50%              28.000000          93.000000          98.000000
75%              70.000000         231.000000         247.000000
max           41748.000000       81194.000000      136971.000000

       units_mf_500_walk   pop_500_walk    hh_500_walk  poor_500_walk  \
count      415716.000000  415716.000000  415716.000000  415716.000000
mean          165.668030     792.460144     315.900543      85.833946
std           469.333771    2241.259277     956.908142     320.218262
min             0.000000       0.000000       0.000000       0.000000
25%             0.000000      20.000000       7.000000       1.000000
50%             2.000000     462.000000     170.000000      25.000000
75%           159.000000    1085.000000     395.000000      83.000000
max         48024.000000  396980.000000  162471.000000   42785.000000

              ...           jobs_2500_walk_retail  jobs_500_walk_fire  \
count         ...                   415716.000000       415716.000000
mean          ...                     1581.148926           53.822426
std           ...                     3031.134277          428.136566
min           ...                        0.000000            0.000000
25%           ...                      223.000000            0.000000
50%           ...                      842.000000            3.000000
75%           ...                     1990.000000           23.000000
max           ...                    35938.000000        20526.000000

       jobs_1500_walk_fire  jobs_2500_walk_fire  jobs_500_walk_tech  \
count        415716.000000        415716.000000       415716.000000
mean            420.108704           979.885498          106.462120
std            1995.809814          3202.999268          790.943481
min               0.000000             0.000000            0.000000
25%              19.000000           113.000000            0.000000
50%             101.000000           366.000000            4.000000
75%             278.000000           857.000000           30.000000
max           34682.000000         38378.000000        31572.000000

       jobs_1500_walk_tech  jobs_2500_walk_tech  jobs_500_walk_serv  \
count        415716.000000        415716.000000       415716.000000
mean            815.707397          1950.819824           60.115826
std            3808.567383          6458.846680          270.231689
min               0.000000             0.000000            0.000000
25%              25.000000           126.000000            0.000000
50%             117.000000           455.000000            0.000000
75%             463.000000          1449.000000           35.000000
max           68294.000000         77926.000000        12480.000000

       jobs_1500_walk_serv  jobs_2500_walk_serv
count        415716.000000        415716.000000
mean            436.379059          1104.810425
std            1438.846191          2959.999268
min               0.000000             0.000000
25%              12.000000           116.000000
50%             126.000000           494.000000
75%             416.000000          1107.000000
max           25447.000000         34317.000000

[8 rows x 55 columns]
Time to execute step 'network_aggregations_walk': 270.01 s
Total time to execute iteration 1 with iteration value None: 270.01 s

### List the tables and columns you can now use for model estimation

In [5]:
for table_name in orca.list_tables():
    print(table_name.upper())
    print(orca.get_table(table_name).to_frame().columns.tolist())
    print()

PARCELS
['development_type_id', 'land_value', 'acres', 'county_id', 'zone_id', 'proportion_undevelopable', 'tax_exempt_status', 'apn', 'parcel_id_local', 'geom_id', 'imputation_flag', 'x', 'y', 'shape_area', 'block_id', 'node_id', 'node_id_small', 'node_id_walk']

BUILDINGS
['parcel_id', 'development_type_id', 'improvement_value', 'residential_units', 'residential_sqft', 'sqft_per_unit', 'non_residential_sqft', 'building_sqft', 'nonres_rent_per_sqft', 'res_price_per_sqft', 'stories', 'year_built', 'redfin_sale_price', 'redfin_sale_year', 'redfin_home_type', 'costar_property_type', 'costar_rent', 'building_type_id', 'res_sqft_per_unit', 'node_id_small', 'node_id_walk']

CRAIGSLIST
['date', 'region', 'neighborhood', 'rent', 'bedrooms', 'sqft', 'rent_sqft', 'longitude', 'latitude', 'county', 'fips_block', 'state', 'bathrooms']

RENTALS
['Unnamed: 0', 'date', 'region', 'neighborhood', 'rent', 'bedrooms', 'sqft', 'rent_sqft', 'longitude', 'latitude', 'county', 'fips_block', 'state', 'bathrooms', 'node_id_small', 'node_id_walk']

UNITS
['building_id', 'num_units', 'tenure', 'unit_num', 'unit_residential_price', 'unit_residential_rent', 'node_id_small', 'node_id_walk']

HOUSEHOLDS
['serialno', 'persons', 'building_type', 'cars', 'income', 'race_of_head', 'hispanic_head', 'age_of_head', 'workers', 'state', 'county', 'tract', 'block_group', 'children', 'tenure', 'recent_mover', 'block_group_id', 'single_family', 'unit_id', 'building_id', 'node_id_small', 'node_id_walk']

PERSONS
['member_id', 'age', 'relate', 'edu', 'sex', 'hours', 'hispanic', 'earning', 'race_id', 'household_id', 'student', 'work_at_home', 'worker', 'node_id_small', 'node_id_walk']

JOBS
['building_id', 'sector_id', 'occupation_id', 'node_id_small', 'node_id_walk']

NODESSMALL
['units_10000', 'units_sf_10000', 'units_mf_10000', 'pop_10000', 'hh_10000', 'poor_10000', 'renters_10000', 'avg_income_10000', 'jobs_10000', 'avg_rent_10000', 'pop_white_10000', 'pop_black_10000', 'pop_asian_10000', 'pop_hisp_10000', 'units_25000', 'units_sf_25000', 'units_mf_25000', 'pop_25000', 'hh_25000', 'poor_25000', 'renters_25000', 'avg_income_25000', 'jobs_25000', 'avg_rent_25000', 'pop_white_25000', 'pop_black_25000', 'pop_asian_25000', 'pop_hisp_25000', 'jobs_10000_retail', 'jobs_25000_retail', 'jobs_10000_fire', 'jobs_25000_fire', 'jobs_10000_tech', 'jobs_25000_tech', 'jobs_10000_serv', 'jobs_25000_serv']

NODESWALK
['units_500_walk', 'sqft_unit_500_walk', 'singles_500_walk', 'elderly_hh_500_walk', 'children_500_walk', 'units_sf_500_walk', 'units_mf_500_walk', 'pop_500_walk', 'hh_500_walk', 'poor_500_walk', 'rich_500_walk', 'renters_500_walk', 'avg_income_500_walk', 'jobs_500_walk', 'avg_rent_500_walk', 'pop_white_500_walk', 'pop_black_500_walk', 'pop_asian_500_walk', 'pop_hisp_500_walk', 'units_1500_walk', 'sqft_unit_1500_walk', 'singles_1500_walk', 'elderly_hh_1500_walk', 'children_1500_walk', 'units_sf_1500_walk', 'units_mf_1500_walk', 'pop_1500_walk', 'hh_1500_walk', 'poor_1500_walk', 'rich_1500_walk', 'renters_1500_walk', 'avg_income_1500_walk', 'jobs_1500_walk', 'avg_rent_1500_walk', 'pop_white_1500_walk', 'pop_black_1500_walk', 'pop_asian_1500_walk', 'pop_hisp_1500_walk', 'pop_2500_walk', 'pop_white_2500_walk', 'pop_black_2500_walk', 'pop_asian_2500_walk', 'pop_hisp_2500_walk', 'jobs_500_walk_retail', 'jobs_1500_walk_retail', 'jobs_2500_walk_retail', 'jobs_500_walk_fire', 'jobs_1500_walk_fire', 'jobs_2500_walk_fire', 'jobs_500_walk_tech', 'jobs_1500_walk_tech', 'jobs_2500_walk_tech', 'jobs_500_walk_serv', 'jobs_1500_walk_serv', 'jobs_2500_walk_serv']

### List the pre-defined merge relationships between tables

In [6]:
orca.list_broadcasts()

[('parcels', 'buildings'),
 ('buildings', 'units'),
 ('units', 'households'),
 ('households', 'persons'),
 ('buildings', 'jobs'),
 ('nodeswalk', 'parcels'),
 ('nodeswalk', 'rentals'),
 ('nodessmall', 'rentals'),
 ('nodessmall', 'parcels')]

### View the contents of a single table

In [8]:
orca.get_table('buildings').to_frame().describe()

,parcel_id,development_type_id,improvement_value,residential_units,residential_sqft,sqft_per_unit,non_residential_sqft,building_sqft,nonres_rent_per_sqft,res_price_per_sqft,stories,year_built,redfin_sale_price,redfin_sale_year,building_type_id,res_sqft_per_unit,node_id_small,node_id_walk
count,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.824229e+06,1.081100e+06,1.081100e+06,1.824229e+06,1.715474e+06,1.824229e+06,1.824229e+06
mean,1.012861e+06,1.835162e+00,3.186878e+05,1.534000e+00,2.657113e+03,1.669294e+03,1.280864e+03,3.784462e+03,9.218572e-01,2.927191e+02,1.214429e+00,1.965524e+03,5.287307e+05,2.002828e+03,1.710299e+00,1.781741e+03,7.901671e+08,8.926345e+08
std,5.938065e+05,3.441080e+00,3.571671e+06,6.137263e+00,3.012408e+04,1.063476e+03,2.392226e+04,3.494568e+04,4.053916e+00,2.647712e+02,5.567798e-01,2.501754e+01,7.188123e+05,7.143867e+00,2.396463e+00,6.803636e+03,1.400113e+09,1.622640e+09
min,2.600000e+01,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.790000e+03,0.000000e+00,1.962000e+03,0.000000e+00,1.015556e+02,2.812660e+05,2.545794e+07
25%,4.958500e+05,1.000000e+00,8.267503e+04,1.000000e+00,1.230000e+03,1.176000e+03,0.000000e+00,1.320000e+03,0.000000e+00,1.518671e+02,1.000000e+00,1.952000e+03,2.390000e+05,1.998000e+03,1.000000e+00,1.200000e+03,5.788284e+07,5.789370e+07
50%,1.002691e+06,1.000000e+00,1.675535e+05,1.000000e+00,1.754000e+03,1.564000e+03,0.000000e+00,1.858000e+03,0.000000e+00,2.544594e+02,1.000000e+00,1.966000e+03,4.000000e+05,2.004000e+03,1.000000e+00,1.626000e+03,6.550126e+07,6.551237e+07
75%,1.532117e+06,1.000000e+00,2.853423e+05,1.000000e+00,2.400000e+03,2.029424e+03,0.000000e+00,2.524000e+03,0.000000e+00,3.699121e+02,1.000000e+00,1.983000e+03,6.500000e+05,2.009000e+03,1.000000e+00,2.042000e+03,6.120713e+08,4.161833e+08
max,2.054501e+06,2.400000e+01,3.355514e+09,1.912000e+03,1.458000e+07,3.000000e+04,1.657310e+07,1.458000e+07,1.289625e+02,5.016109e+04,5.900000e+01,2.015000e+03,1.800000e+08,2.014000e+03,1.600000e+01,7.283880e+06,5.458527e+09,5.471137e+09